### PR TITLE
Fix redis conf file path

### PR DESCRIPTION
**Pull request by ethuleau**
On Ubuntu 12.04 the redis configuration file path is '/etc/redis/redis.conf' and not '/etc/redis.conf'

### CODE REVIEW

**Comment by frank-borkin** [comment]
You should probably wrap this in a "if is_ubuntu; then" and set the config path to a var.

**Comment by ethuleau** [comment]
Done.
I don't set the config path to a var.
What do you mean ?

**Comment by frank-borkin** [comment]
I mean somewhere should be a section

if is_ubuntu
REDIS_CONF = "/etc/redis/redis.conf"
else
blah

and later

screen_it redis $REDIS_CONF

I think there will be more than 1 config file different between RHEL and Ubuntu, and later we might want to support other distro's (SuSE?)

**Comment by dsetia** [comment]
Edouard, thanks for your suggestion. Can you make config path changes based on platform as suggested by Frank?

**Comment by ethuleau** [comment]
Like this ?

**Comment by ethuleau** [comment]
My fix seems more useful since the marge: https://github.com/dsetia/devstack/commit/fa41a4386251cf5d71f5226d72adc839ee02a953

I remove it ?

**Comment by dsetia** [comment]
Doude, Most of your original fix should have been incorporated. If yes, can you retract it? Else can you submit a new pull request as new changes have come in since you submitted original pull request.

**Pull request closed without merging**
